#include "main.h"

/* =========================================================
   LCD I2C CONFIGURATION
   NUCLEO-F446RE

   PB8 -> I2C1_SCL
   PB9 -> I2C1_SDA

   LCD VCC -> 5V
   LCD GND -> GND
   ========================================================= */

#define LCD_ADDR        (0x27 << 1)

/* PCF8574 LCD backpack mapping */
#define LCD_RS          0x01
#define LCD_EN          0x04
#define LCD_BACKLIGHT   0x08


/* =========================================================
   LCD FUNCTION PROTOTYPES
   ========================================================= */

void LCD_Init(void);
void LCD_SendCommand(uint8_t cmd);
void LCD_SendData(uint8_t data);
void LCD_SendString(char *str);
void LCD_SetCursor(uint8_t row, uint8_t column);
void LCD_Clear(void);

static void LCD_SendNibble(uint8_t nibble, uint8_t rs);
static void LCD_PulseEnable(uint8_t data);


/* =========================================================
   SEND NIBBLE
   ========================================================= */

static void LCD_SendNibble(uint8_t nibble, uint8_t rs)
{
    uint8_t data;

    data = nibble | LCD_BACKLIGHT;

    if (rs)
        data |= LCD_RS;
    else
        data &= ~LCD_RS;

    HAL_I2C_Master_Transmit(
        &hi2c1,
        LCD_ADDR,
        &data,
        1,
        HAL_MAX_DELAY
    );

    LCD_PulseEnable(data);
}


/* =========================================================
   ENABLE PULSE
   ========================================================= */

static void LCD_PulseEnable(uint8_t data)
{
    uint8_t temp;

    /* EN = HIGH */

    temp = data | LCD_EN;

    HAL_I2C_Master_Transmit(
        &hi2c1,
        LCD_ADDR,
        &temp,
        1,
        HAL_MAX_DELAY
    );

    HAL_Delay(1);


    /* EN = LOW */

    temp = data & ~LCD_EN;

    HAL_I2C_Master_Transmit(
        &hi2c1,
        LCD_ADDR,
        &temp,
        1,
        HAL_MAX_DELAY
    );

    HAL_Delay(1);
}


/* =========================================================
   SEND COMMAND
   ========================================================= */

void LCD_SendCommand(uint8_t cmd)
{
    uint8_t upper;
    uint8_t lower;

    upper = cmd & 0xF0;
    lower = (cmd << 4) & 0xF0;

    LCD_SendNibble(upper, 0);
    LCD_SendNibble(lower, 0);

    HAL_Delay(2);
}


/* =========================================================
   SEND CHARACTER
   ========================================================= */

void LCD_SendData(uint8_t data)
{
    uint8_t upper;
    uint8_t lower;

    upper = data & 0xF0;
    lower = (data << 4) & 0xF0;

    LCD_SendNibble(upper, 1);
    LCD_SendNibble(lower, 1);

    HAL_Delay(1);
}


/* =========================================================
   SEND STRING
   ========================================================= */

void LCD_SendString(char *str)
{
    while (*str != '\0')
    {
        LCD_SendData((uint8_t)*str);
        str++;
    }
}


/* =========================================================
   CLEAR LCD
   ========================================================= */

void LCD_Clear(void)
{
    LCD_SendCommand(0x01);
    HAL_Delay(2);
}


/* =========================================================
   SET CURSOR

   row = 0 -> first line
   row = 1 -> second line

   column = 0 to 15
   ========================================================= */

void LCD_SetCursor(uint8_t row, uint8_t column)
{
    uint8_t address;

    if (row == 0)
    {
        address = 0x80 + column;
    }
    else
    {
        address = 0xC0 + column;
    }

    LCD_SendCommand(address);
}


/* =========================================================
   LCD INITIALIZATION
   ========================================================= */

void LCD_Init(void)
{
    HAL_Delay(50);

    /* Force LCD into 4-bit mode */

    LCD_SendNibble(0x30, 0);
    HAL_Delay(5);

    LCD_SendNibble(0x30, 0);
    HAL_Delay(1);

    LCD_SendNibble(0x30, 0);
    HAL_Delay(1);

    LCD_SendNibble(0x20, 0);
    HAL_Delay(1);


    /* 4-bit mode, 2 lines, 5x8 font */

    LCD_SendCommand(0x28);


    /* Display OFF */

    LCD_SendCommand(0x08);


    /* Clear display */

    LCD_SendCommand(0x01);
    HAL_Delay(2);


    /* Entry mode */

    LCD_SendCommand(0x06);


    /* Display ON, cursor OFF */

    LCD_SendCommand(0x0C);
}


/* =========================================================
   MAIN
   ========================================================= */

int main(void)
{
    /* HAL initialization */

    HAL_Init();


    /* System clock
       KEEP THE FUNCTION GENERATED BY CUBEIDE */

    SystemClock_Config();


    /* GPIO
       KEEP THE FUNCTION GENERATED BY CUBEIDE */

    MX_GPIO_Init();


    /* I2C1
       KEEP THE FUNCTION GENERATED BY CUBEIDE */

    MX_I2C1_Init();


    /* Initialize LCD */

    LCD_Init();


    /* Display first line */

    LCD_SetCursor(0, 0);
    LCD_SendString("Hello STM32");


    /* Display second line */

    LCD_SetCursor(1, 0);
    LCD_SendString("F446RE LCD");


    while (1)
    {
        /* Main application */

    }
}
